### ISSUE TITLE
python 2

### ISSUE THREAD

**Issue by kegl** [ramp-kits/vertex_finding#2]
pls make sure that the starting kit works also in Python 2.

```
mbp-kuomo:vertex_finding kegl$ ramp_test_submission 
Traceback (most recent call last):
  File "/Users/kegl/anaconda/bin/ramp_test_submission", line 11, in <module>
    load_entry_point('ramp-workflow', 'console_scripts', 'ramp_test_submission')()
  File "/Users/kegl/Research/RAMP/ramp-workflow/rampwf/utils/command_line.py", line 104, in ramp_test_submission
    retrain=retrain)
  File "/Users/kegl/Research/RAMP/ramp-workflow/rampwf/utils/testing.py", line 79, in assert_submission
    problem = assert_read_problem(ramp_kit_dir)
  File "/Users/kegl/Research/RAMP/ramp-workflow/rampwf/utils/testing.py", line 31, in assert_read_problem
    os.path.join(ramp_kit_dir, 'problem.py'))
  File "./problem.py", line 387
    velo_states = [VeloState(*h['ClosestToBeam'], *h['errCTBState'])  for key,h in VeloTracks.items() ]
                                                  ^
SyntaxError: invalid syntax
```

**Comment by aboucaud** [comment]
Fixed by commit https://github.com/ramp-kits/vertex_finding/commit/7c05af364f1cdca030b0e400c9dab050bacd37fa
