### ISSUE TITLE
Non-breaking space character breaks pretty_print?

### ISSUE THREAD

**Issue by VukanJ** [ramp-kits/vertex_finding#5]
When running the test script, there seems to be a problem involving character \xa0 (non-breaking space?) which is passed to pretty print. Is there an easy workaround for this issue, or did I miss something? Here is the complete output: 
```
(vertex_finding) ➜  vertex_finding git:(master) ramp_test_submission --quick-test
Testing RAPID challenge
Reading train and test files from ./data ...
Reading cv ...
Training ./submissions/starting_kit ...
CV fold 0
        score  total  efficiency  fake rate  z resolution  effective efficiency
        train  29.13        0.02       0.99          0.11                  0.01
        valid  29.13        0.02       0.99          0.11                  0.01
        test   25.24        0.01       0.99          0.13                  0.01
----------------------------
Mean CV scores
----------------------------
Traceback (most recent call last):
  File "/home/vukan/.local/anaconda3/envs/vertex_finding/bin/ramp_test_submission", line 11, in <module>
    sys.exit(ramp_test_submission())
  File "/home/vukan/.local/anaconda3/envs/vertex_finding/lib/python3.6/site-packages/rampwf/utils/command_line.py", line 93, in ramp_test_submission
    retrain=retrain)
  File "/home/vukan/.local/anaconda3/envs/vertex_finding/lib/python3.6/site-packages/rampwf/utils/testing.py", line 130, in assert_submission
    print_df_scores(df_mean_scores, score_types, indent='\t')
  File "/home/vukan/.local/anaconda3/envs/vertex_finding/lib/python3.6/site-packages/rampwf/utils/pretty_print.py", line 80, in print_df_scores
    print('\n'.join(df_repr_out))
UnicodeEncodeError: 'ascii' codec can't encode character'\xa0'  in position 146: ordinal not in range(128)
```

**Comment by VukanJ** [comment]
Solved. The locale environment variable was not set correctly
